### ISSUE TITLE
Should ship a default configuration

### ISSUE THREAD

**Issue by clounie** [nextworld-tools/GoLocal2#1]
Nextworld code has started on a common port for a long time. We should ship a default configuration, which will:
1. Make it easier for people to start using GoLocal
2. Provide an example as a starting point for people to create other configurations

**Comment by MrAaronOlsen** [comment]
Instead of shipping a new one I might default new urls with local host.

**Comment by clounie** [comment]
@MrAaronOlsen what about port?

**Comment by MrAaronOlsen** [comment]
When you add a new URL all fields are defaulted to Name - Local, Port = 8080, and Url = http://localhost
